### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by govindsa1011** [SimonMarquis/AR-Toolbox#3]
I clone the repository to my system and try to run in android studio but its not have any module for run the project.

**Comment by wukaihong** [comment]
I want to add a filter to the camera, similar to adding a black and white filter. The whole camera preview is gray, and then render the 3D model. I don't know how to do it. Can you give me some ideas or suggestions? thank you

**Comment by tabraizjawed** [comment]
> I clone the repository to my system and try to run in android studio but its not have any module for run the project.

Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64

Update to this android studio version. it starts work..
