### ISSUE TITLE
Help & Suggestion

### ISSUE THREAD

**Issue by jokersci** [SimonMarquis/AR-Toolbox#5]
thanks for this amazing sample 
need  help plz 
can you scale object to x,y,z axis's  by seekbar  
coz no need to use touch view or can you Guide me how I can do that

**Comment by SimonMarquis** [comment]
Hi, thanks for the suggestion but unfortunately I won't add such interaction into this sample.
You can take a look at the `TransformableNode` that contains a `ScaleController` which is responsible for scaling.
It uses `setLocalScale(Vector3)` with a `Vector3` parameter that corresponds to the 3 axis you can control.
