### ISSUE TITLE
AssertionError("Unable to create RenderableInstance.");

### ISSUE THREAD

**Issue by PuppiesMeat** [SimonMarquis/AR-Toolbox#7]
Hi , I found some error when run this application.
This exception post from RenderableInternalData#buildInstanceData ! Can i get the source code?    api 'com.google.ar.sceneform:rendering:1.17.1'

**Comment by SimonMarquis** [comment]
Hi, can you paste the whole stacktrace you've got here?

> Can i get the source code?

It's available here: https://github.com/google-ar/sceneform-android-sdk
